/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SplashRouteImport } from './routes/splash'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PaywallFullRouteImport } from './routes/paywall/full'
import { Route as AppRewardsRouteImport } from './routes/_app/rewards'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppMeRouteImport } from './routes/_app/me'
import { Route as AppLeaderboardRouteImport } from './routes/_app/leaderboard'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppChatRouteImport } from './routes/_app/chat'
import { Route as AppLearnIndexRouteImport } from './routes/_app/learn/index'
import { Route as AppQuizQuizIdRouteImport } from './routes/_app/quiz.$quizId'
import { Route as AppExploreCategoryIdRouteImport } from './routes/_app/explore.$categoryId'
import { Route as AppChatNewRouteImport } from './routes/_app/chat.new'
import { Route as AppChatChatIdRouteImport } from './routes/_app/chat.$chatId'
import { Route as AppLearnMilestoneIdIndexRouteImport } from './routes/_app/learn/$milestoneId/index'
import { Route as LessonMilestoneIdLevelIdLessonIdRouteImport } from './routes/lesson.$milestoneId.$levelId.$lessonId'
import { Route as LessonLoadingMilestoneIdLevelIdLessonIdRouteImport } from './routes/lesson-loading.$milestoneId.$levelId.$lessonId'
import { Route as AppLearnMilestoneIdLevelIdRouteImport } from './routes/_app/learn/$milestoneId/$levelId'

const SplashRoute = SplashRouteImport.update({
  id: '/splash',
  path: '/splash',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PaywallFullRoute = PaywallFullRouteImport.update({
  id: '/paywall/full',
  path: '/paywall/full',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRewardsRoute = AppRewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppMeRoute = AppMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AppRoute,
} as any)
const AppLeaderboardRoute = AppLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppLearnIndexRoute = AppLearnIndexRouteImport.update({
  id: '/learn/',
  path: '/learn/',
  getParentRoute: () => AppRoute,
} as any)
const AppQuizQuizIdRoute = AppQuizQuizIdRouteImport.update({
  id: '/quiz/$quizId',
  path: '/quiz/$quizId',
  getParentRoute: () => AppRoute,
} as any)
const AppExploreCategoryIdRoute = AppExploreCategoryIdRouteImport.update({
  id: '/explore/$categoryId',
  path: '/explore/$categoryId',
  getParentRoute: () => AppRoute,
} as any)
const AppChatNewRoute = AppChatNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppChatRoute,
} as any)
const AppChatChatIdRoute = AppChatChatIdRouteImport.update({
  id: '/$chatId',
  path: '/$chatId',
  getParentRoute: () => AppChatRoute,
} as any)
const AppLearnMilestoneIdIndexRoute =
  AppLearnMilestoneIdIndexRouteImport.update({
    id: '/learn/$milestoneId/',
    path: '/learn/$milestoneId/',
    getParentRoute: () => AppRoute,
  } as any)
const LessonMilestoneIdLevelIdLessonIdRoute =
  LessonMilestoneIdLevelIdLessonIdRouteImport.update({
    id: '/lesson/$milestoneId/$levelId/$lessonId',
    path: '/lesson/$milestoneId/$levelId/$lessonId',
    getParentRoute: () => rootRouteImport,
  } as any)
const LessonLoadingMilestoneIdLevelIdLessonIdRoute =
  LessonLoadingMilestoneIdLevelIdLessonIdRouteImport.update({
    id: '/lesson-loading/$milestoneId/$levelId/$lessonId',
    path: '/lesson-loading/$milestoneId/$levelId/$lessonId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppLearnMilestoneIdLevelIdRoute =
  AppLearnMilestoneIdLevelIdRouteImport.update({
    id: '/learn/$milestoneId/$levelId',
    path: '/learn/$milestoneId/$levelId',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/splash': typeof SplashRoute
  '/chat': typeof AppChatRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/leaderboard': typeof AppLeaderboardRoute
  '/me': typeof AppMeRoute
  '/profile': typeof AppProfileRoute
  '/rewards': typeof AppRewardsRoute
  '/paywall/full': typeof PaywallFullRoute
  '/chat/$chatId': typeof AppChatChatIdRoute
  '/chat/new': typeof AppChatNewRoute
  '/explore/$categoryId': typeof AppExploreCategoryIdRoute
  '/quiz/$quizId': typeof AppQuizQuizIdRoute
  '/learn/': typeof AppLearnIndexRoute
  '/learn/$milestoneId/$levelId': typeof AppLearnMilestoneIdLevelIdRoute
  '/lesson-loading/$milestoneId/$levelId/$lessonId': typeof LessonLoadingMilestoneIdLevelIdLessonIdRoute
  '/lesson/$milestoneId/$levelId/$lessonId': typeof LessonMilestoneIdLevelIdLessonIdRoute
  '/learn/$milestoneId/': typeof AppLearnMilestoneIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/splash': typeof SplashRoute
  '/chat': typeof AppChatRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/leaderboard': typeof AppLeaderboardRoute
  '/me': typeof AppMeRoute
  '/profile': typeof AppProfileRoute
  '/rewards': typeof AppRewardsRoute
  '/paywall/full': typeof PaywallFullRoute
  '/chat/$chatId': typeof AppChatChatIdRoute
  '/chat/new': typeof AppChatNewRoute
  '/explore/$categoryId': typeof AppExploreCategoryIdRoute
  '/quiz/$quizId': typeof AppQuizQuizIdRoute
  '/learn': typeof AppLearnIndexRoute
  '/learn/$milestoneId/$levelId': typeof AppLearnMilestoneIdLevelIdRoute
  '/lesson-loading/$milestoneId/$levelId/$lessonId': typeof LessonLoadingMilestoneIdLevelIdLessonIdRoute
  '/lesson/$milestoneId/$levelId/$lessonId': typeof LessonMilestoneIdLevelIdLessonIdRoute
  '/learn/$milestoneId': typeof AppLearnMilestoneIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/splash': typeof SplashRoute
  '/_app/chat': typeof AppChatRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/leaderboard': typeof AppLeaderboardRoute
  '/_app/me': typeof AppMeRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/rewards': typeof AppRewardsRoute
  '/paywall/full': typeof PaywallFullRoute
  '/_app/chat/$chatId': typeof AppChatChatIdRoute
  '/_app/chat/new': typeof AppChatNewRoute
  '/_app/explore/$categoryId': typeof AppExploreCategoryIdRoute
  '/_app/quiz/$quizId': typeof AppQuizQuizIdRoute
  '/_app/learn/': typeof AppLearnIndexRoute
  '/_app/learn/$milestoneId/$levelId': typeof AppLearnMilestoneIdLevelIdRoute
  '/lesson-loading/$milestoneId/$levelId/$lessonId': typeof LessonLoadingMilestoneIdLevelIdLessonIdRoute
  '/lesson/$milestoneId/$levelId/$lessonId': typeof LessonMilestoneIdLevelIdLessonIdRoute
  '/_app/learn/$milestoneId/': typeof AppLearnMilestoneIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/splash'
    | '/chat'
    | '/dashboard'
    | '/leaderboard'
    | '/me'
    | '/profile'
    | '/rewards'
    | '/paywall/full'
    | '/chat/$chatId'
    | '/chat/new'
    | '/explore/$categoryId'
    | '/quiz/$quizId'
    | '/learn/'
    | '/learn/$milestoneId/$levelId'
    | '/lesson-loading/$milestoneId/$levelId/$lessonId'
    | '/lesson/$milestoneId/$levelId/$lessonId'
    | '/learn/$milestoneId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/splash'
    | '/chat'
    | '/dashboard'
    | '/leaderboard'
    | '/me'
    | '/profile'
    | '/rewards'
    | '/paywall/full'
    | '/chat/$chatId'
    | '/chat/new'
    | '/explore/$categoryId'
    | '/quiz/$quizId'
    | '/learn'
    | '/learn/$milestoneId/$levelId'
    | '/lesson-loading/$milestoneId/$levelId/$lessonId'
    | '/lesson/$milestoneId/$levelId/$lessonId'
    | '/learn/$milestoneId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/splash'
    | '/_app/chat'
    | '/_app/dashboard'
    | '/_app/leaderboard'
    | '/_app/me'
    | '/_app/profile'
    | '/_app/rewards'
    | '/paywall/full'
    | '/_app/chat/$chatId'
    | '/_app/chat/new'
    | '/_app/explore/$categoryId'
    | '/_app/quiz/$quizId'
    | '/_app/learn/'
    | '/_app/learn/$milestoneId/$levelId'
    | '/lesson-loading/$milestoneId/$levelId/$lessonId'
    | '/lesson/$milestoneId/$levelId/$lessonId'
    | '/_app/learn/$milestoneId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  SignupRoute: typeof SignupRoute
  SplashRoute: typeof SplashRoute
  PaywallFullRoute: typeof PaywallFullRoute
  LessonLoadingMilestoneIdLevelIdLessonIdRoute: typeof LessonLoadingMilestoneIdLevelIdLessonIdRoute
  LessonMilestoneIdLevelIdLessonIdRoute: typeof LessonMilestoneIdLevelIdLessonIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/splash': {
      id: '/splash'
      path: '/splash'
      fullPath: '/splash'
      preLoaderRoute: typeof SplashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paywall/full': {
      id: '/paywall/full'
      path: '/paywall/full'
      fullPath: '/paywall/full'
      preLoaderRoute: typeof PaywallFullRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/rewards': {
      id: '/_app/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof AppRewardsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/me': {
      id: '/_app/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof AppMeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leaderboard': {
      id: '/_app/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AppLeaderboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chat': {
      id: '/_app/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/learn/': {
      id: '/_app/learn/'
      path: '/learn'
      fullPath: '/learn/'
      preLoaderRoute: typeof AppLearnIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/quiz/$quizId': {
      id: '/_app/quiz/$quizId'
      path: '/quiz/$quizId'
      fullPath: '/quiz/$quizId'
      preLoaderRoute: typeof AppQuizQuizIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/explore/$categoryId': {
      id: '/_app/explore/$categoryId'
      path: '/explore/$categoryId'
      fullPath: '/explore/$categoryId'
      preLoaderRoute: typeof AppExploreCategoryIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chat/new': {
      id: '/_app/chat/new'
      path: '/new'
      fullPath: '/chat/new'
      preLoaderRoute: typeof AppChatNewRouteImport
      parentRoute: typeof AppChatRoute
    }
    '/_app/chat/$chatId': {
      id: '/_app/chat/$chatId'
      path: '/$chatId'
      fullPath: '/chat/$chatId'
      preLoaderRoute: typeof AppChatChatIdRouteImport
      parentRoute: typeof AppChatRoute
    }
    '/_app/learn/$milestoneId/': {
      id: '/_app/learn/$milestoneId/'
      path: '/learn/$milestoneId'
      fullPath: '/learn/$milestoneId/'
      preLoaderRoute: typeof AppLearnMilestoneIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/lesson/$milestoneId/$levelId/$lessonId': {
      id: '/lesson/$milestoneId/$levelId/$lessonId'
      path: '/lesson/$milestoneId/$levelId/$lessonId'
      fullPath: '/lesson/$milestoneId/$levelId/$lessonId'
      preLoaderRoute: typeof LessonMilestoneIdLevelIdLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lesson-loading/$milestoneId/$levelId/$lessonId': {
      id: '/lesson-loading/$milestoneId/$levelId/$lessonId'
      path: '/lesson-loading/$milestoneId/$levelId/$lessonId'
      fullPath: '/lesson-loading/$milestoneId/$levelId/$lessonId'
      preLoaderRoute: typeof LessonLoadingMilestoneIdLevelIdLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/learn/$milestoneId/$levelId': {
      id: '/_app/learn/$milestoneId/$levelId'
      path: '/learn/$milestoneId/$levelId'
      fullPath: '/learn/$milestoneId/$levelId'
      preLoaderRoute: typeof AppLearnMilestoneIdLevelIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppChatRouteChildren {
  AppChatChatIdRoute: typeof AppChatChatIdRoute
  AppChatNewRoute: typeof AppChatNewRoute
}

const AppChatRouteChildren: AppChatRouteChildren = {
  AppChatChatIdRoute: AppChatChatIdRoute,
  AppChatNewRoute: AppChatNewRoute,
}

const AppChatRouteWithChildren =
  AppChatRoute._addFileChildren(AppChatRouteChildren)

interface AppRouteChildren {
  AppChatRoute: typeof AppChatRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppLeaderboardRoute: typeof AppLeaderboardRoute
  AppMeRoute: typeof AppMeRoute
  AppProfileRoute: typeof AppProfileRoute
  AppRewardsRoute: typeof AppRewardsRoute
  AppExploreCategoryIdRoute: typeof AppExploreCategoryIdRoute
  AppQuizQuizIdRoute: typeof AppQuizQuizIdRoute
  AppLearnIndexRoute: typeof AppLearnIndexRoute
  AppLearnMilestoneIdLevelIdRoute: typeof AppLearnMilestoneIdLevelIdRoute
  AppLearnMilestoneIdIndexRoute: typeof AppLearnMilestoneIdIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppChatRoute: AppChatRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppLeaderboardRoute: AppLeaderboardRoute,
  AppMeRoute: AppMeRoute,
  AppProfileRoute: AppProfileRoute,
  AppRewardsRoute: AppRewardsRoute,
  AppExploreCategoryIdRoute: AppExploreCategoryIdRoute,
  AppQuizQuizIdRoute: AppQuizQuizIdRoute,
  AppLearnIndexRoute: AppLearnIndexRoute,
  AppLearnMilestoneIdLevelIdRoute: AppLearnMilestoneIdLevelIdRoute,
  AppLearnMilestoneIdIndexRoute: AppLearnMilestoneIdIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  SignupRoute: SignupRoute,
  SplashRoute: SplashRoute,
  PaywallFullRoute: PaywallFullRoute,
  LessonLoadingMilestoneIdLevelIdLessonIdRoute:
    LessonLoadingMilestoneIdLevelIdLessonIdRoute,
  LessonMilestoneIdLevelIdLessonIdRoute: LessonMilestoneIdLevelIdLessonIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
